purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2365591
  brandStrength: 1
  lightness: 0.672043
  brandColors:
    - '#a9adb0'
    - '#ecedf1'
    - '#818284'
    - '#50483a'
    - '#a27d42'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Singularity studio
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.47361
layout_spectrum: 0.49249
