name: Singularity studio
favicon: null
layout_spectrum: 0.50835
typography_spectrum: 0.16813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9adb0'
    - '#ecedf1'
    - '#818284'
    - '#50483a'
    - '#a27d42'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
