name: Singularitystudio
favicon: null
layout_spectrum: 0.0648
typography_spectrum: 0.16813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2931'
    - '#4d626c'
    - '#fecf93'
    - '#d8a26b'
    - '#defecf'
  brandStrength: 0.6185486519243568
  lightness: 0.375
  saturation: 0.20710704009979963
  rhythmicContrast: 0.43653451511636376
purpose: []
