name: Singularitystudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#645c5a'
    - '#ffcda8'
    - '#262a2a'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.43653451511636376
purpose: []
